services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
