openapi: 3.0.3
info:
  title: Adaptive Components API
  description: API documentation for the portfolio's adaptive components
  version: 0.25.51
  contact:
    name: Ralph Bernard Serrano
    url: https://va-ralphbserrano.github.io/va-rb-portfolio/

tags:
  - name: AdaptiveImage
    description: Image component with responsive loading and format optimization
  - name: AdaptiveContainer
    description: Smart container with responsive layout and performance optimization

components:
  schemas:
    ResponsiveValue:
      type: object
      properties:
        base:
          oneOf:
            - type: string
            - type: number
          description: Base value for the responsive property
        sm:
          oneOf:
            - type: string
            - type: number
          description: Value for small viewport (≥640px)
        md:
          oneOf:
            - type: string
            - type: number
          description: Value for medium viewport (≥768px)
        lg:
          oneOf:
            - type: string
            - type: number
          description: Value for large viewport (≥1024px)
        xl:
          oneOf:
            - type: string
            - type: number
          description: Value for extra large viewport (≥1280px)
      required:
        - base

    Breakpoints:
      type: object
      properties:
        sm:
          type: number
          description: Small viewport breakpoint
          default: 640
        md:
          type: number
          description: Medium viewport breakpoint
          default: 768
        lg:
          type: number
          description: Large viewport breakpoint
          default: 1024
        xl:
          type: number
          description: Extra large viewport breakpoint
          default: 1280

    PerformanceConfig:
      type: object
      properties:
        monitorResize:
          type: boolean
          description: Enable resize monitoring
          default: true
        debounceDelay:
          type: number
          description: Delay for debouncing resize events (ms)
          default: 150
        optimizeReflows:
          type: boolean
          description: Enable reflow optimization
          default: true

    AdaptiveImageProps:
      type: object
      properties:
        src:
          type: string
          description: Source URL of the image
        alt:
          type: string
          description: Alt text for accessibility
        sizes:
          type: string
          description: Sizes attribute for responsive images
          default: 100vw
        loading:
          type: string
          enum: [lazy, eager]
          description: Loading strategy
          default: lazy
        quality:
          type: number
          minimum: 1
          maximum: 100
          description: Image quality (1-100)
          default: 85
        placeholder:
          type: string
          description: Placeholder image URL
        formats:
          type: array
          items:
            type: string
            enum: [webp, avif, jpeg, png]
          description: Supported formats in order of preference
          default: [webp, avif, jpeg]
        className:
          type: string
          description: Custom CSS class
      required:
        - src
        - alt

    AdaptiveContainerProps:
      type: object
      properties:
        minWidth:
          oneOf:
            - type: string
            - type: number
          description: Minimum container width
          default: auto
        maxWidth:
          oneOf:
            - type: string
            - type: number
          description: Maximum container width
          default: 100%
        padding:
          oneOf:
            - type: string
            - type: number
            - $ref: '#/components/schemas/ResponsiveValue'
          description: Container padding
          default: 1rem
        margin:
          oneOf:
            - type: string
            - type: number
            - $ref: '#/components/schemas/ResponsiveValue'
          description: Container margin
          default: "0"
        breakpoints:
          $ref: '#/components/schemas/Breakpoints'
          description: Custom breakpoint configuration
        behavior:
          type: string
          enum: [fluid, fixed, hybrid]
          description: Container behavior type
          default: fluid
        performance:
          $ref: '#/components/schemas/PerformanceConfig'
          description: Performance configuration
        className:
          type: string
          description: Custom CSS class

paths:
  /components/adaptive/AdaptiveImage:
    get:
      tags:
        - AdaptiveImage
      summary: Get AdaptiveImage component
      description: Returns the AdaptiveImage React component
      responses:
        '200':
          description: AdaptiveImage component
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdaptiveImageProps'

  /components/adaptive/AdaptiveContainer:
    get:
      tags:
        - AdaptiveContainer
      summary: Get AdaptiveContainer component
      description: Returns the AdaptiveContainer React component
      responses:
        '200':
          description: AdaptiveContainer component
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdaptiveContainerProps'
