name: Fix TypeScript Type Errors

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  fix-type-errors:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create scripts directory
      run: mkdir -p scripts

    - name: Check for type errors
      id: type-check
      run: |
        npx tsc --noEmit || echo "TYPE_ERRORS=true" >> $GITHUB_ENV

    - name: Fix type errors
      if: env.TYPE_ERRORS == 'true'
      run: |
        node scripts/fix-type-errors.js
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Verify fixes
      run: npx tsc --noEmit

    - name: Commit and push changes
      if: env.TYPE_ERRORS == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "fix: automated type error fixes"
        git push
